/* 1. CREATE TABLE */

CREATE TABLE ITEM_MASTER(
ID VARCHAR2(5),
NAME VARCHAR2(20),
TYPE VARCHAR2(20),
PRICE NUMBER(6),
QUALITY VARCHAR2(15),
ITEM_PACK_DATE DATE
);


/* 2. INSERT DATA */

INSERT INTO ITEM_MASTER VALUES('I1','DAIRYMILK','CHOCOLATE',500,'GOOD',TO_DATE('12-AUG-2000','DD-MON-YYYY'));

INSERT INTO ITEM_MASTER VALUES('I2','KAJUKATRI','MITHAI',1000,'VERYGOOD',TO_DATE('15-JAN-2016','DD-MON-YYYY'));

INSERT INTO ITEM_MASTER VALUES('I3','PIZZA','FASTFOOD',350,'AVERAGE',TO_DATE('20-FEB-2015','DD-MON-YYYY'));

INSERT INTO ITEM_MASTER VALUES('I4','ORANGEJUICE','JUICE',50,'BEST',TO_DATE('05-FEB-2016','DD-MON-YYYY'));

INSERT INTO ITEM_MASTER VALUES('I5','VANILLA_CAKE','BAKERY',2000,'GOOD',TO_DATE('01-JAN-2016','DD-MON-YYYY'));

COMMIT;


/* 3. SELECT PRICE, QUALITY, ITEM_PACK_DATE */

SELECT PRICE, QUALITY, ITEM_PACK_DATE
FROM ITEM_MASTER;


/* 4. DISPLAY ALL INFORMATION */

SELECT * 
FROM ITEM_MASTER;


/* 5. SORT ITEM BY QUALITY */

SELECT *
FROM ITEM_MASTER
ORDER BY QUALITY;


/* 6. DISTINCT QUALITY VALUES */

SELECT DISTINCT QUALITY
FROM ITEM_MASTER;


/* 7. CHANGE QUALITY GOOD → VERYGOOD */

UPDATE ITEM_MASTER
SET QUALITY='VERYGOOD'
WHERE QUALITY='GOOD';

COMMIT;


/* 8. DISPLAY ITEMS HAVING QUALITY VERYGOOD */

SELECT *
FROM ITEM_MASTER
WHERE QUALITY='VERYGOOD';


/* 9. ADD NEW COLUMN ITEM_PUR_DATE */

ALTER TABLE ITEM_MASTER
ADD ITEM_PUR_DATE DATE;


/* 10. DISPLAY ITEMS HAVING PRICE > 500 */

SELECT *
FROM ITEM_MASTER
WHERE PRICE > 500;


/* 11. DELETE ITEM HAVING PRICE = 50 */

DELETE FROM ITEM_MASTER
WHERE PRICE = 50;

COMMIT;


/* 12. RENAME TABLE ITEM_MASTER TO ITEM_DETAIL */

RENAME ITEM_MASTER TO ITEM_DETAIL;