/* 1. CREATE TABLE */

CREATE TABLE CUST_MASTER(
CUST_NO VARCHAR2(5),
CUST_NAME VARCHAR2(20),
ADDRESS1 VARCHAR2(30),
ADDRESS2 VARCHAR2(30),
CITY VARCHAR2(20),
STATE VARCHAR2(20),
PH_NO NUMBER(12)
);


/* 2. INSERT DATA */

INSERT INTO CUST_MASTER VALUES('C1','PRIYA','RINGROAD','PUJA PARK','AHMEDABAD','GUJARAT',8989878548);

INSERT INTO CUST_MASTER VALUES('C2','PUJA','LAJPAT NAGAR','SHYAMAL COLONY','BANARAS','UP',7898456213);

INSERT INTO CUST_MASTER VALUES('C3','ANKIT','BORIVALI','PANCHAYAT NAGAR','MUMBAI','MAHARASHTRA',7885984251);

INSERT INTO CUST_MASTER VALUES('C4','RAVI','VAJDIROAD','NANDBHOOMI COLONY','DELHI','DELHI',7898452034);

INSERT INTO CUST_MASTER VALUES('C5','ALPA','JAMNAGAR ROAD','RAILWAY COLONY','AHMEDABAD','GUJARAT',7465241589);

COMMIT;


/* 3. SELECT ALL CUSTOMERS */

SELECT *
FROM CUST_MASTER;


/* 4. CUSTOMERS FROM GUJARAT */

SELECT *
FROM CUST_MASTER
WHERE STATE='GUJARAT';


/* 5. SORT CUSTOMERS BY NAME */

SELECT *
FROM CUST_MASTER
ORDER BY CUST_NAME;


/* 6. DISTINCT CITY VALUES */

SELECT DISTINCT CITY
FROM CUST_MASTER;


/* 7. CHANGE ADDRESS1 OF PRIYA */

UPDATE CUST_MASTER
SET ADDRESS1='CG ROAD'
WHERE CUST_NAME='PRIYA';

COMMIT;


/* 8. DISPLAY CITY OF CUSTOMERS FROM GUJARAT */

SELECT CITY
FROM CUST_MASTER
WHERE STATE='GUJARAT';


/* 9. ADD NEW COLUMN PIN_CODE */

ALTER TABLE CUST_MASTER
ADD PIN_CODE NUMBER(6);


/* 10. DROP COLUMN PIN_CODE */

ALTER TABLE CUST_MASTER
DROP COLUMN PIN_CODE;


/* 11. DELETE CUSTOMER WITH PHONE NO */

DELETE FROM CUST_MASTER
WHERE PH_NO=7898452034;

COMMIT;


/* 12. RENAME TABLE */

RENAME CUST_MASTER TO CUSTOMER_DETAIL;