/* 1. CREATE TABLE */

CREATE TABLE PERSON(
PERSON_ID NUMBER(5),
FNAME VARCHAR2(20),
LNAME VARCHAR2(20),
CITY VARCHAR2(20),
SALARY NUMBER(10)
);


/* 2. INSERT DATA */

INSERT INTO PERSON VALUES(1,'SNEHA','SHETH','RAJKOT',10000);
INSERT INTO PERSON VALUES(2,'PUJA','PARMAR','AHMEDABAD',2000);
INSERT INTO PERSON VALUES(3,'RIYA','GAJAR','PUNE',8000);
INSERT INTO PERSON VALUES(4,'SANDIP','JADEJA','PUNE',5000);
INSERT INTO PERSON VALUES(5,'ALPESH','PRAJAPATI','MUMBAI',20000);

COMMIT;


/* 3. SELECT PERSON_ID AND FNAME */

SELECT PERSON_ID, FNAME
FROM PERSON;


/* 4. DISPLAY ALL PERSON */

SELECT *
FROM PERSON;


/* 5. SORT PERSON BY SALARY */

SELECT *
FROM PERSON
ORDER BY SALARY;


/* 6. DISTINCT CITY */

SELECT DISTINCT CITY
FROM PERSON;


/* 7. CHANGE CITY OF SANDIP FROM PUNE TO KOLKATA */

UPDATE PERSON
SET CITY='KOLKATA'
WHERE FNAME='SANDIP';

COMMIT;


/* 8. DISPLAY PERSON WHOSE LNAME IS PRAJAPATI */

SELECT *
FROM PERSON
WHERE LNAME='PRAJAPATI';


/* 9. ADD NEW COLUMNS */

ALTER TABLE PERSON
ADD STATE VARCHAR2(20);

ALTER TABLE PERSON
ADD BIRTHDATE DATE;

ALTER TABLE PERSON
ADD PINCODE NUMBER(6);


/* 10. PERSON HAVING SALARY > 6000 */

SELECT *
FROM PERSON
WHERE SALARY > 6000;


/* 11. DELETE PERSON HAVING SALARY < 3000 */

DELETE FROM PERSON
WHERE SALARY < 3000;

COMMIT;


/* 12. RENAME TABLE */

RENAME PERSON TO PERSON_MASTER;