/* 1. CREATE TABLE */

CREATE TABLE BANK_BRANCH(
BRANCH_ID VARCHAR2(10),
BRANCH_NAME VARCHAR2(20),
BRANCH_ADDRESS VARCHAR2(30),
BRANCH_CITY VARCHAR2(20),
BRANCH_STATE VARCHAR2(20),
BRANCH_OPEN_DATE DATE
);


/* 2. INSERT DATA */

INSERT INTO BANK_BRANCH VALUES('B001','BOI','BORIWALI ROAD','MUMBAI','MAHARASHTRA',
TO_DATE('12-JAN-2000','DD-MON-YYYY'));

INSERT INTO BANK_BRANCH VALUES('B002','SBI','JAGNATH ROAD','RAJKOT','GUJARAT',
TO_DATE('22-MAR-2015','DD-MON-YYYY'));

INSERT INTO BANK_BRANCH VALUES('B003','HDFC','AGRA ROAD','AGRA','UP',
TO_DATE('04-FEB-1998','DD-MON-YYYY'));

INSERT INTO BANK_BRANCH VALUES('B004','DENA BANK','CG ROAD','AHMEDABAD','GUJARAT',
TO_DATE('20-SEP-2012','DD-MON-YYYY'));

INSERT INTO BANK_BRANCH VALUES('B005','ICICI','MAJAVDI ROAD','JUNAGADH','GUJARAT',
TO_DATE('07-MAY-2011','DD-MON-YYYY'));

COMMIT;


/* 3. DISPLAY ALL INFORMATION */

SELECT *
FROM BANK_BRANCH;


/* 4. DISPLAY BRANCH_ID */

SELECT BRANCH_ID
FROM BANK_BRANCH;


/* 5. DISPLAY BRANCH_ID AND BRANCH_ADDRESS */

SELECT BRANCH_ID, BRANCH_ADDRESS
FROM BANK_BRANCH;


/* 6. DISPLAY BRANCH_NAME, BRANCH_ADDRESS, BRANCH_CITY */

SELECT BRANCH_NAME, BRANCH_ADDRESS, BRANCH_CITY
FROM BANK_BRANCH;


/* 7. DISPLAY BRANCH_CITY, BRANCH_STATE, BRANCH_OPEN_DATE */

SELECT BRANCH_CITY, BRANCH_STATE, BRANCH_OPEN_DATE
FROM BANK_BRANCH;


/* 8. SORT BY BRANCH_ID */

SELECT *
FROM BANK_BRANCH
ORDER BY BRANCH_ID;


/* 9. SORT BY BRANCH_NAME */

SELECT *
FROM BANK_BRANCH
ORDER BY BRANCH_NAME;


/* 10. SORT BY BRANCH_CITY */

SELECT *
FROM BANK_BRANCH
ORDER BY BRANCH_CITY;


/* 11. SORT BY BRANCH_STATE */

SELECT *
FROM BANK_BRANCH
ORDER BY BRANCH_STATE;